[package]
name = "fluffy-fiesta"
version = "0.1.0"
authors = ["Remi Rampin <remirampin@gmail.com>"]

[[bin]]
name = "client"

[dependencies]
vecmath = "0.2.*"

# Abstract graphics
piston = "0.25.*"
piston2d-graphics = "0.17.*"
conrod = "0.43.*"
piston_window = "0.52"

# Concrete graphics
sdl2 = "*"
pistoncore-sdl2_window = "0.34.*"

[features]
use_sdl2_mac_framework = ["sdl2/use_mac_framework"]
