[package]
name = "fluffy-fiesta"
version = "0.1.0"
authors = ["Remi Rampin <remirampin@gmail.com>"]

[[bin]]
name = "client"

[dependencies]
piston = "0.25.*"
piston2d-graphics = "0.17.*"
pistoncore-glutin_window = "0.30.*"
piston2d-opengl_graphics = "0.33.*"
