[package]
name = "fluffy-fiesta"
version = "0.1.0"
authors = ["Remi Rampin <remirampin@gmail.com>"]
license = "BSD-3-Clause"
repository = "https://github.com/remram44/fluffy-fiesta"
description = "Platformer game with Piston"
readme = "README.md"
keywords = ["game", "platformer"]

[[bin]]
name = "client"
path = "src/main.rs"

[dependencies]
env_logger = "0.4"
log = "0.3"
vecmath = "0.3"

# Abstract graphics
conrod = { version = "0.56", features = ["piston"] }
piston = "0.35"
piston2d-graphics = "0.23"

# Concrete graphics
piston2d-opengl_graphics = "0.49"
pistoncore-sdl2_window = "0.46"
sdl2 = "0.30"

[features]
use_sdl2_mac_framework = ["sdl2/use_mac_framework"]
